### ISSUE TITLE
Will DML_OPERATOR_CONVOLUTION support fuse relu6?

### ISSUE THREAD

**Issue by calvinlcchen** [MicrosoftDocs/windows-ai-docs#46] opened 2021-11-26 10:44 UTC
[Enter feedback here]
Somewhen Relu6 is better than Relu. Will Relu6 be planed to supported for fusion with DML_OPERATOR_CONVOLUTION?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 887dba1c-254f-69ce-9ec1-06a85252cb59
* Version Independent ID: 50219630-91f2-e788-36a8-96831534655f
* Content: [Using fused operators to improve performance](https://docs.microsoft.com/en-us/windows/ai/directml/dml-fused-activations)
* Content Source: [docs/directml/dml-fused-activations.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/dml-fused-activations.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2021-11-27 03:08
Hi, @calvinlcchen, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions regarding the product itself (the APIs in this case), like this, one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action that I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2021-11-27 03:08 UTC
